[package]
name = "surfdesk-core"
version = "0.1.0"
edition = "2021"
description = "Core library for SurfDesk - Multi-platform Solana Account Studio"
license = "MIT"
repository = "https://github.com/your-org/surfdesk"

[dependencies]
# Dioxus framework
dioxus = { workspace = true }
dioxus-router = { workspace = true }
dioxus-signals = { workspace = true }

# Additional dependencies
env_logger = "0.10"
libc = "0.2"
async-trait = "0.1"

# Solana ecosystem
solana-sdk = { workspace = true, optional = true }
solana-client = { workspace = true, optional = true }
solana-account-decoder = { workspace = true, optional = true }
anchor-lang = { workspace = true, optional = true }
anchor-client = { workspace = true, optional = true }

# Async runtime and utilities
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = "0.8"
uuid = { workspace = true }

# Database
diesel = { workspace = true, optional = true }
diesel_migrations = { workspace = true, optional = true }
chrono = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Configuration
config = { workspace = true }

# Logging
log = { workspace = true }
console_log = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }
dirs = "6.0.0"
# solana-transaction-status = "3.0.6"  # Temporarily commented out due to zeroize conflicts
zeroize = { version = "=1.3.0", features = ["alloc"] }

[dev-dependencies]
proptest = { workspace = true }
tokio-test = "0.4"

[features]
default = ["database", "solana"]
database = ["diesel", "diesel_migrations"]
solana = ["solana-sdk", "solana-client", "solana-account-decoder", "anchor-lang", "anchor-client"]
web = ["dioxus/web", "console_log", "wasm-bindgen", "web-sys"]
desktop = ["dioxus/desktop"]
tui = []
